1 function year pricing
image-charts/website pull request #2
Opened 2019-05-14 08:42 UTC by AugustinRibreau

addition of the month/year function

2019-05-14 09:48 UTC, FGRibreau requested changes

2019-05-14 09:48 UTC, FGRibreau commented on app/_pricing.pug
> +        div#cost.pricing__price 529€/year
pourquoi cet ajout d'id ? un `document.querySelectorAll('.pricing__price').forEach(el => el.innerText = "XXX€/YYY")` permettra d'accéder à tous les éléments en `.pricing__price` (utile si il y a plusieurs endroits où tu veux afficher le prix)

2019-05-14 09:48 UTC, FGRibreau commented on app/_pricing.pug
> +        .promo → Save 10%
`.promo` pas BEM-compliant

2019-05-14 09:48 UTC, FGRibreau commented on app/_pricing.pug
> +        input#month(type='radio', name='options')
Ca fonctionne aussi sous safari/edge/firefox ?

2019-05-14 09:48 UTC, FGRibreau commented on app/_pricing.pug
> +        input#month(type='radio', name='options')
l'id "month" est trop générique, il faut trouver un nom plus spécifique e.g. "#pricing_by_month" idem pour `#year`

2019-05-14 09:48 UTC, FGRibreau commented on app/_pricing.pug
> +        a#urlChang.btn.btn__primary(href="https://image-charts.com/enterprise/customers?plan_id=enterprise-yearly-2016") Subscribe now
en plus d'être non valide en anglais (il manque un "e") `urlChang` ne décrit pas ce qu'est ce lien, "#plan_subscription_url"  serait plus adéquate

2019-05-14 09:48 UTC, FGRibreau commented on app/script/pricing.js
> +    if (cost.innerHTML == "529€/year" && urlChang.href == "https://image-charts.com/enterprise/customers?plan_id=enterprise-yearly-2016") {
le code est quasiment le même entre la ligne 7-10 et la ligne 14-17, trouve un moyen de factoriser.

Pour factoriser, les fonctions sont tes amis.

Tips: utilise une fonction **qui prends en paramètre** un `cost` (e.g. "529€/year") et un `plan_id` e.g. "enterprise-yearly-2016") et donc le **rôle** est de changer l'affichage du coût et l'adresse de l'URL.

2019-05-14 09:48 UTC, FGRibreau commented on app/scss/components/_pricing.scss
> +#month, #year{
ici on voit que #month et #year ne sont pas préfixé/scopé, c'est dangereux, car d'autres composants pourrait avoir #month et #year comme identifiants. On voit donc qu'ils ne sont pas assez précis et trop générique (donc dangereux)

2019-05-14 09:48 UTC, FGRibreau commented on app/scss/components/_pricing.scss
> +.promo{
même remarque

2019-05-14 12:05 UTC, AugustinRibreau commented on app/_pricing.pug
> +        input#month(type='radio', name='options')
> Ca fonctionne aussi sous safari/edge/firefox ?

J'ai essayer edge et oui, je n'ai pas firefox ni safari. Un site pour avoir tous les navigateurs ?(oui) mais surtout pour essayer un projet local ?

2019-05-14 12:37 UTC, FGRibreau commented on app/_pricing.pug
> +        input#month(type='radio', name='options')
> Un site pour avoir tous les navigateurs ?(oui) mais surtout pour essayer un projet local ?

pas compris

2019-05-14 12:59 UTC, AugustinRibreau commented on app/_pricing.pug
> +        input#month(type='radio', name='options')
Je ne vais pas installer sur mon pc 40 navigateurs webs juste pour tester un site. Il n'y a pas un site qui émule toutes sortes de navigateurs ?

2019-05-14 13:29 UTC, AugustinRibreau commented on app/_pricing.pug
> +        div#cost.pricing__price 529€/year
Le problème du `querySelectorAll` c'est qu'il donne une NodeList, donc il faut sélectionner la bonne ligne cette avec "529€/year" dedans, le soucis c'est qu'il a beau avoir la valeur et tout, ensuite impossible de rentrer dans le if.. c'est pour ça que j'ai rajouter un id

2019-05-14 14:32 UTC, FGRibreau commented on app/_pricing.pug
> +        div#cost.pricing__price 529€/year
Pardon:

```js
Array.from(document.querySelectorAll('.pricing__price')).forEach(el => el.innerText = "XXX€/YYY")
```

:+1:

2019-05-14 15:32 UTC, AugustinRibreau commented on app/_pricing.pug
> +        div#cost.pricing__price 529€/year
> ```js
> Array.from(document.querySelectorAll('.pricing__price')).forEach(el => el.innerText = "XXX€/YYY")
> ```
Maintenant il remplace tout par XXX€/YYY
Je t'avoue que je tourne un peu en rond depuis tout à l'heure

2019-05-14 17:25 UTC, FGRibreau commented on app/_pricing.pug
> +        label.btn.btn__primary.btn__pricing.btn__pricing--right(for='pricing_by_year')
plutôt que --left et --right, pourquoi ne pas utiliser `.pricing-switch label:first-child` et `.pricing-switch label:last-child`

https://quirksmode.org/css/selectors/firstchild.html

2019-05-14 17:25 UTC, FGRibreau commented on app/_pricing.pug
> +        .pricing_by_promo → Save 10%
`.pricing_by_promo` -> `.pricing_discount` car `by_promo` ne veut pas dire grand chose

2019-05-14 17:28 UTC, FGRibreau commented on app/_pricing.pug
> +        div#pricing__price.pricing__price 529€/year
vu que c'est un id, il faut être plus précis, ici ça pourrait être `.js-enterprise-price` + `document.querySelector('.js-enterprise-price')`.

Le ".js-*" est une convention habituelle pour préciser sémantiquement que *cette class css là* sera accédée depuis javascript et qu'il ne faut pas l'utiliser comme class css pour du styling (cf: https://medium.freecodecamp.org/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849 )

2019-05-14 17:29 UTC, FGRibreau commented on app/_pricing.pug
> +        a#plan_subscription_url.btn.btn__primary(href="https://image-charts.com/enterprise/customers?plan_id=enterprise-yearly-2016") Subscribe now
même remarque, plutôt qu'un id, passer par un nom de classe css en ".js-*" c'est moins contraignant pour le naming. E.g. `a.js-enterprise-subscription-url`

2019-05-14 17:31 UTC, FGRibreau commented on app/_pricing.pug
> +        input#pricing_by_month(type='radio', name='options')
value="monthly"

2019-05-14 17:31 UTC, FGRibreau commented on app/_pricing.pug
> +        input#pricing_by_year(type='radio', name='options', checked='')
value="yearly"

2019-05-14 17:35 UTC, FGRibreau commented on app/script/pricing.js
> +monthButton.addEventListener("click", function(){
```js
document.getElementById('pricing_by_month').addEventListener("change", function(){
// quel est l'input actuellement sélectionné

// prendre le bon couple cost/plan_id dans l'array ci-dessous en fonction de "interval==monthly|yearly" (utiliser plans.find(...) pour cela)
const plans = [{
cost: '49€/month',
plan_id: 'enterprise-2016',
interval: 'monthly'
},{
cost: '529€/year',
plan_id: 'enterprise-yearly-2016',
interval: 'yearly'
}];

// changer cost & plan_subscription_url
});
```

J'avais demandé dans un commentaire précédent une fonction qui n'existe pas ici 😡
Il faut l'implémenter et l'appeler.

2019-05-15 07:59 UTC, AugustinRibreau commented on app/_pricing.pug
> +        label.btn.btn__primary.btn__pricing.btn__pricing--right(for='pricing_by_year')
Fait mais avec des 
```CSS
.pricing-switch li:nth-child(1) label{}
```

2019-05-15 10:23 UTC, FGRibreau commented on app/script/pricing.js
> +// [Input, Input]
remove

2019-05-15 10:23 UTC, FGRibreau commented on app/script/pricing.js
> +    .forEach(input => input.addEventListener("change", function (event) {
change `function (event)` to a lambda expression

2019-05-15 10:46 UTC, FGRibreau approved these changes

2019-05-15 11:00 UTC, merged